import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: 'Arquitetura (C4)',
      collapsed: false,
      items: ['architecture/overview'],
    },
    {
      type: 'category',
      label: 'ADRs',
      items: [{ type: 'autogenerated', dirName: 'adrs' }],
    },
    {
      type: 'category',
      label: 'RFCs',
      items: [{ type: 'autogenerated', dirName: 'rfcs' }],
    },
  ],
};

export default sidebars;
